[package]
name = "network_observant"
version = "0.1.0"
authors = ["vvbv"]

[dependencies]
postgres = "0.15.2"
chrono = "0.4.6"
postgres-shared = "0.4.2"

[[bin]]
name = "network_observant"
path = "main.rs"